### ISSUE TITLE
Site Design Studio site doesn't load correctly

### ISSUE THREAD

**Issue by Ochechule** [pnp/sp-site-designs-studio#15] opened 2020-09-13 22:01 UTC
Hi ,
Site Design Studio sites stopped working in all 3 tenants where we use it. It stopped working on Friday in Asia/Australia tenants and over the weekend in EU tenant. 

When the site is loaded, new (plus) buttons appear for a second and then disappear and the page is blank (screenshot attached).
![screen](https://user-images.githubusercontent.com/65981697/93029486-48b75a80-f66f-11ea-8076-605d804a3216.png)

Errors that I can see in browser dev tools: 
```
VM10201:34 A preload for 'https://XXX.sharepoint.com/sites/apps/ClientSideAssets/83580513-8ac2-4fdc-89f5-5f44e4364309/sp-site-designs-studio-sitedesignsstudiowebpartstrings_en-us_aaa100775270daa7b4d9b6985e640feb.js' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.

VM10201:34 A preload for 'https://XXX.sharepoint.com/sites/apps/ClientSideAssets/83580513-8ac2-4fdc-89f5-5f44e4364309/sp-site-designs-studio-controlstrings_en-us_1e961a41cbc896aaaeae4fd7637791a8.js' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.

VM10201:34 A preload for 'https://XXX.sharepoint.com/sites/apps/ClientSideAssets/83580513-8ac2-4fdc-89f5-5f44e4364309/site-designs-studio_dcecc2845696da59c3bfea039b9d314a.js' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.

sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1 POST https://XXX.sharepoint.com/_api/Microsoft.Sharepoint.Utilities.WebTemplateExtensions.SiteScriptUtility.GetSiteDesigns 400 (Bad Request)

sp-pages-assembly_en-us_0a1c05f5e3bd0bdb1beb2cb00167ccfa.js:1 POST https://XXX.sharepoint.com/_api/Microsoft.Sharepoint.Utilities.WebTemplateExtensions.SiteScriptUtility.GetSiteScripts 400 (Bad Request)
```

We are using SDS v2.0.1.0. Tested in different browsers. Is this something related to some SharePoint update?

Thank you,
Pavel

**Comment by ypcode** [comment] 2020-09-14 05:43
Hello,

It might be indeed a change in the API, on my end I did not change anything recently.

I will have a look soon. In the mean time, in case I could not reproduce it, can you please find the call to GetSiteDesigns in the F12 Network tab, and copy here the response content?

Thx in advance
Yannick

**Comment by Ochechule** [comment] 2020-09-14 06:13
Hi Yannick,
this is the response (the same in all tenants):
https://XXXX.sharepoint.com/_api/Microsoft.Sharepoint.Utilities.WebTemplateExtensions.SiteScriptUtility.GetSiteDesigns
`{"error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":"Cannot handle the data at position 0."}}`
Thanks, Pavel

**Comment by ypcode** [comment] 2020-09-14 06:25
That is indeed not normal :)
I will figure out if it's a breaking change or a bug on MS side, and eventually provide a fix ASAP

**Comment by ypcode** [comment] 2020-09-14 21:18
Hello @Ochechule,

There seems to be a change in the API compared to how I initially implemented it.
Anyway, trying it with PnP JS helped me figure out how to address this issue and I just provided a small fix that should make it work now.

I issued a v2.0.2.0 , you can download the latest package [here ](https://github.com/pnp/sp-site-designs-studio/tree/master/setup/package)

Simply drop it in your app catalog and that should do it  :) 
Let me know how it goes!

Best regards,
Yannick

**Comment by Ochechule** [comment] 2020-09-14 21:46
Hi Yannick,
fantastic, thank you! I have deployed it in two tenants and did a few tests and everything seems to be working fine.

Kind regards,
Pavel

**Comment by ypcode** [comment] 2020-09-14 22:05
Perfect ! Closing the issue :)

**Closed by ypcode** 2020-09-14 22:05 UTC
